import { createClient } from '@supabase/supabase-js';

export const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
async function fail(error) { throw new Error(error?.message || 'Error de Supabase'); }
async function ok(data) { return { data }; }
const now = () => Date.now();
const dataUrl = (type, base64) => base64 ? `data:${type};base64,${base64}` : '';

async function getData() {
  const [cats,responses,settings,instructions,templates,backups] = await Promise.all([
    supabase.from('crm_categories').select('*').order('name'),
    supabase.from('crm_responses').select('*').order('updated_at',{ascending:false}),
    supabase.from('crm_settings').select('*').limit(1).maybeSingle(),
    supabase.from('crm_instructions').select('*').order('created_at',{ascending:false}),
    supabase.from('crm_certificate_templates').select('id,name,description,filename,path,content_type,size,created_at,updated_at').order('created_at',{ascending:false}),
    supabase.from('crm_certificate_backups').select('*').order('created_at',{ascending:false})
  ]);
  for (const r of [cats,responses,settings,instructions,templates,backups]) if (r.error) await fail(r.error);
  const raw=settings.data?.data||{};
  const settingsOut={
    institution_name:raw.institution_name||'Fundación Universitaria Compensar',
    logo_url:raw.logo_data?dataUrl(raw.logo_content_type||'image/png',raw.logo_data):((raw.logo_url&&/^https?:\/\//.test(raw.logo_url))?raw.logo_url:''),
    logo_path:raw.logo_path||'', background_image_url:raw.background_data?dataUrl(raw.background_content_type||'image/jpeg',raw.background_data):(raw.background_image_url||'/resources/fondo-ucompensar.png'),
    background_path:raw.background_path||'', background_type:raw.background_type||'image',
    background_video_url:raw.background_video_data?dataUrl(raw.background_video_content_type||'video/mp4',raw.background_video_data):(raw.background_video_url||''),
    background_video_path:raw.background_video_path||'', background_transparency:typeof raw.background_transparency==='number'?raw.background_transparency:88,
    primary_color:raw.primary_color||'#FF6801',accent_color:raw.accent_color||'#4E2A54',background_color:raw.background_color||'#F6F7F9',
    topbar_mode:raw.topbar_mode||'solid',topbar_color_1:raw.topbar_color_1||'#FFFFFF',topbar_color_2:raw.topbar_color_2||'#FFFFFF',topbar_color_3:raw.topbar_color_3||'#FFFFFF',
    sidebar_mode:raw.sidebar_mode||'gradient',sidebar_color_1:raw.sidebar_color_1||'#4E2A54',sidebar_color_2:raw.sidebar_color_2||'#6E5E9D',sidebar_color_3:raw.sidebar_color_3||'#1896A8',
    topbar_font_family:raw.topbar_font_family||'ui-rounded',sidebar_font_family:raw.sidebar_font_family||'ui-rounded',
    hero_mode:raw.hero_mode||'gradient',hero_color_1:raw.hero_color_1||'#4E2A54',hero_color_2:raw.hero_color_2||'#6E5E9D',hero_color_3:raw.hero_color_3||'#FF6801',hero_font_family:raw.hero_font_family||'ui-rounded'
  };
  const instructionItems=(instructions.data||[]).map(item=>({...item,url:dataUrl(item.content_type||'application/octet-stream',item.content_base64||'')}));
  return {categories:cats.data||[],responses:responses.data||[],settings:settingsOut,instructions:instructionItems,certificate_templates:templates.data||[],certificate_backups:backups.data||[]};
}
const DEFAULT_ADMIN_PASSWORD = 'UCOMPENSAR2026';
async function checkPassword(password) { const {data,error}=await supabase.from('crm_settings').select('data').limit(1).maybeSingle(); if(error) await fail(error); return Boolean((data?.data?.admin_password || DEFAULT_ADMIN_PASSWORD) === password); }
async function requirePassword(password) { if(!await checkPassword(password)) throw new Error('No autorizado'); }
async function request(method,url,body) {
  const clean=url.split('?')[0];
  if(method==='GET'&&clean==='/api/data') return ok(await getData());
  if(method==='POST'&&clean==='/api/admin/login') return ok({ok:await checkPassword(body?.password||'')});
  if(method==='POST'&&clean==='/api/categories'){await requirePassword(body?.password);const{data,error}=await supabase.from('crm_categories').insert({name:String(body.name||'').trim()}).select().single();if(error)await fail(error);return ok({ok:true,category:data});}
  let m=clean.match(/^\/api\/categories\/([^/]+)$/);
  if(m&&method==='PUT'){await requirePassword(body?.password);const{data,error}=await supabase.from('crm_categories').update({name:String(body.name||'').trim()}).eq('id',m[1]).select().single();if(error)await fail(error);return ok({ok:true,category:data});}
  if(m&&method==='DELETE'){await requirePassword(body?.password);const{error:e1}=await supabase.from('crm_responses').delete().eq('category_id',m[1]);if(e1)await fail(e1);const{error:e2}=await supabase.from('crm_categories').delete().eq('id',m[1]);if(e2)await fail(e2);return ok({ok:true});}
  if(method==='POST'&&clean==='/api/responses'){await requirePassword(body?.password);const{data,error}=await supabase.from('crm_responses').insert({category_id:body.category_id,title:body.title,keywords:body.keywords||'',text:body.text,instruction_id:body.instruction_id||null,updated_at:now()}).select().single();if(error)await fail(error);return ok({ok:true,response:data});}
  m=clean.match(/^\/api\/responses\/([^/]+)$/);
  if(m&&method==='PUT'){await requirePassword(body?.password);const{data,error}=await supabase.from('crm_responses').update({category_id:body.category_id,title:body.title,keywords:body.keywords||'',text:body.text,instruction_id:body.instruction_id||null,updated_at:now()}).eq('id',m[1]).select().single();if(error)await fail(error);return ok({ok:true,response:data});}
  m=clean.match(/^\/api\/responses\/([^/]+)\/delete$/);
  if(m&&method==='POST'){await requirePassword(body?.password);const{error}=await supabase.from('crm_responses').delete().eq('id',m[1]);if(error)await fail(error);return ok({ok:true});}
  if(method==='PUT'&&clean==='/api/settings'){await requirePassword(body?.password);const{data:current,error:e}=await supabase.from('crm_settings').select('*').limit(1).maybeSingle();if(e)await fail(e);const next={...(current?.data||{}),...body};delete next.password;const{error}=await supabase.from('crm_settings').upsert(current?.id?{id:current.id,data:next}:{data:next});if(error)await fail(error);return ok({ok:true});}
  if(method==='POST'&&clean==='/api/settings/upload'){await requirePassword(body?.password);const{data:current,error:e}=await supabase.from('crm_settings').select('*').limit(1).maybeSingle();if(e)await fail(e);const next={...(current?.data||{})};if(body.kind==='logo'){next.logo_data=body.data;next.logo_content_type=body.contentType;next.logo_url='';next.logo_path=body.filename||'';}else{next.background_data=body.data;next.background_content_type=body.contentType;next.background_image_url='';next.background_path=body.filename||'';if(String(body.contentType||'').startsWith('video/')){next.background_type='video';next.background_video_data=body.data;next.background_video_content_type=body.contentType;next.background_video_url='';next.background_video_path=body.filename||'';}else next.background_type='image';}const{error}=await supabase.from('crm_settings').upsert(current?.id?{id:current.id,data:next}:{data:next});if(error)await fail(error);return ok({path:body.filename||'',url:dataUrl(body.contentType,body.data)});}
  if(method==='POST'&&clean==='/api/instructivos/upload'){await requirePassword(body?.password);const{data,error}=await supabase.from('crm_instructions').insert({name:body.filename,path:body.filename,content_type:body.contentType,size:Math.round(String(body.data).length*3/4),content_base64:body.data,created_at:now()}).select().single();if(error)await fail(error);return ok({ok:true,instruction:{...data,url:dataUrl(body.contentType,body.data)}});}
  m=clean.match(/^\/api\/instructivos\/([^/]+)\/delete$/);if(m&&method==='POST'){await requirePassword(body?.password);const{error}=await supabase.from('crm_instructions').delete().eq('id',m[1]);if(error)await fail(error);return ok({ok:true});}
  if(method==='POST'&&clean==='/api/certificados/plantillas/upload'){await requirePassword(body?.password);const filename=String(body.filename||'');const ct=filename.toLowerCase().endsWith('.pdf')?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document';const row={name:String(body.name||filename),description:String(body.description||''),filename,path:filename,content_type:ct,size:Math.round(String(body.data).length*3/4),content_base64:body.data,created_at:now(),updated_at:now()};const{data,error}=await supabase.from('crm_certificate_templates').insert(row).select('id,name,description,filename,path,content_type,size,created_at,updated_at').single();if(error)await fail(error);return ok({ok:true,template:data});}
  m=clean.match(/^\/api\/certificados\/plantillas\/([^/]+)\/file$/);if(m&&method==='GET'){const{data,error}=await supabase.from('crm_certificate_templates').select('content_base64,content_type').eq('id',m[1]).single();if(error)await fail(error);return ok({data:data?.content_base64||'',contentType:data?.content_type||'application/pdf'});}
  m=clean.match(/^\/api\/certificados\/plantillas\/([^/]+)$/);if(m&&method==='PUT'){await requirePassword(body?.password);const{data,error}=await supabase.from('crm_certificate_templates').update({name:String(body.name||''),description:String(body.description||''),updated_at:now()}).eq('id',m[1]).select().single();if(error)await fail(error);return ok({ok:true,template:data});}
  m=clean.match(/^\/api\/certificados\/plantillas\/([^/]+)\/replace$/);if(m&&method==='POST'){await requirePassword(body?.password);const filename=String(body.filename||'');const ct=filename.toLowerCase().endsWith('.pdf')?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document';const{data,error}=await supabase.from('crm_certificate_templates').update({filename,path:filename,content_type:ct,size:Math.round(String(body.data).length*3/4),content_base64:body.data,updated_at:now()}).eq('id',m[1]).select('id,name,description,filename,path,content_type,size,created_at,updated_at').single();if(error)await fail(error);return ok({ok:true,template:data});}
  m=clean.match(/^\/api\/certificados\/plantillas\/([^/]+)\/delete$/);if(m&&method==='POST'){await requirePassword(body?.password);const{error}=await supabase.from('crm_certificate_templates').delete().eq('id',m[1]);if(error)await fail(error);return ok({ok:true});}
  if(method==='POST'&&clean==='/api/certificados/respaldos'){await requirePassword(body?.password);const{data,error}=await supabase.from('crm_certificate_backups').insert({template_id:body.template_id,template_name:body.template_name,filename:body.filename||'',fields:body.fields||{},html:body.html||'',created_at:now()}).select().single();if(error)await fail(error);return ok({ok:true,backup:data});}
  m=clean.match(/^\/api\/certificados\/respaldos\/([^/]+)\/delete$/);if(m&&method==='POST'){await requirePassword(body?.password);const{error}=await supabase.from('crm_certificate_backups').delete().eq('id',m[1]);if(error)await fail(error);return ok({ok:true});}
  if(method==='PUT'&&clean==='/api/admin/password'){await requirePassword(body?.password);if(String(body.new_password||'').length<6)throw new Error('Contraseña inválida');const{data:current,error}=await supabase.from('crm_settings').select('*').limit(1).maybeSingle();if(error)await fail(error);const next={...(current?.data||{}),admin_password:body.new_password};const{error:e}=await supabase.from('crm_settings').upsert(current?.id?{id:current.id,data:next}:{data:next});if(e)await fail(e);return ok({ok:true});}
  if(method==='POST'&&clean==='/api/import'){await requirePassword(body?.password);if(Array.isArray(body.categories)){await supabase.from('crm_categories').delete().neq('id','00000000-0000-0000-0000-000000000000');const{error}=await supabase.from('crm_categories').insert(body.categories.map(x=>({id:x.id,name:x.name})));if(error)await fail(error);}if(Array.isArray(body.responses)){await supabase.from('crm_responses').delete().neq('id','00000000-0000-0000-0000-000000000000');const{error}=await supabase.from('crm_responses').insert(body.responses.map(x=>({id:x.id,category_id:x.category_id,title:x.title,keywords:x.keywords||'',text:x.text,instruction_id:x.instruction_id||null,updated_at:x.updated_at||now()})));if(error)await fail(error);}if(body.settings){const{data:current}=await supabase.from('crm_settings').select('*').limit(1).maybeSingle();const next={...(current?.data||{}),...body.settings};const{error}=await supabase.from('crm_settings').upsert(current?.id?{id:current.id,data:next}:{data:next});if(error)await fail(error);}return ok({ok:true});}
  throw new Error(`Ruta no soportada: ${method} ${url}`);
}
export const api={get:(url)=>request('GET',url),post:(url,body)=>request('POST',url,body),put:(url,body)=>request('PUT',url,body),delete:(url,body)=>request('DELETE',url,body),subscribe:(callback)=>{const channel=supabase.channel('crm-shared').on('postgres_changes',{event:'*',schema:'public',table:'crm_responses'},callback).on('postgres_changes',{event:'*',schema:'public',table:'crm_categories'},callback).on('postgres_changes',{event:'*',schema:'public',table:'crm_settings'},callback).on('postgres_changes',{event:'*',schema:'public',table:'crm_instructions'},callback).on('postgres_changes',{event:'*',schema:'public',table:'crm_certificate_templates'},callback).on('postgres_changes',{event:'*',schema:'public',table:'crm_certificate_backups'},callback).subscribe();return()=>{void supabase.removeChannel(channel);};}};
